#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python


python:
  - 2.7

sudo: false

addons:
    apt:
       packages:
       - liblua5.2-dev


virtualenv:
  system_site_packages: true

before_install:
  - export PYTHONPATH=$HOME/builds/dissemin/wikiciteparser

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=wikiciteparser wikiciteparser/tests.py -v 2

after_success:
  - coveralls

